Facebook Machine Learning video series
https://research.facebook.com/blog/2018/05/the-facebook-field-guide-to-machine-learning-video-series/

Paquetes de datos para experimentar:
https://www.kaggle.com/

#1 - Import the data
#2 - Clean the data
#3 - Split data. Training Set/Test Set
#4 - Create a Model 
#5 - Check the output
#6 - Improve

- usamos jupyter notebook
- biblioteca pandas para manejar archivos de datos
- NumPy para manejar arrays que obtenemos de los archivos

In [9]:
import pandas as pd
data_frame = pd.read_csv('data.csv')
data_frame.shape

(18207, 89)

In [13]:
data_frame

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [12]:
data_frame.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

pandas cheatsheet:
https://colab.research.google.com/github/GokuMohandas/MadeWithML/blob/4ad626098aca25db5628fe67895e738d5a5c2c2a/notebooks/03_Pandas.ipynb#scrollTo=VoMq0eFRvugb
sacada de aca:
https://github.com/GokuMohandas/MadeWithML/blob/4ad626098aca25db5628fe67895e738d5a5c2c2a/notebooks/03_Pandas.ipynb

https://elitedatascience.com/python-cheat-sheet

pandas documentation:
https://pandas.pydata.org/docs/user_guide/index.html#user-guide

hay muchas cosas que se pueden mostrar

In [11]:
data_frame[data_frame["Age"]>38].head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
41,41,1179,G. Buffon,40,https://cdn.sofifa.org/players/4/19/1179.png,Italy,https://cdn.sofifa.org/flags/27.png,88,88,Paris Saint-Germain,...,70.0,13.0,11.0,11.0,88.0,87.0,74.0,90.0,83.0,€7.4M
554,554,49031,S. Sorrentino,39,https://cdn.sofifa.org/players/4/19/49031.png,Italy,https://cdn.sofifa.org/flags/27.png,80,80,Chievo Verona,...,66.0,25.0,10.0,13.0,81.0,82.0,66.0,82.0,79.0,€1.7M
864,864,153260,Hilton,40,https://cdn.sofifa.org/players/4/19/153260.png,Brazil,https://cdn.sofifa.org/flags/54.png,78,78,Montpellier HSC,...,70.0,83.0,77.0,76.0,12.0,7.0,11.0,12.0,13.0,NaN
1120,1120,156092,J. Villar,41,https://cdn.sofifa.org/players/4/19/156092.png,Paraguay,https://cdn.sofifa.org/flags/58.png,77,77,NaN,...,55.0,13.0,13.0,14.0,75.0,75.0,74.0,78.0,77.0,NaN
1294,1294,14907,A. Bizzarri,40,https://cdn.sofifa.org/players/4/19/14907.png,Argentina,https://cdn.sofifa.org/flags/52.png,76,76,Foggia,...,60.0,11.0,12.0,11.0,76.0,74.0,66.0,82.0,76.0,€840K

esto de arriba, por ejemplo, me muestra las primeras personas (head()) cuya edad es mayor a 38

In [15]:
data_frame.sort_values("Age", ascending=False)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
4741,4741,140029,O. Pérez,45,https://cdn.sofifa.org/players/4/19/140029.png,Mexico,https://cdn.sofifa.org/flags/83.png,71,71,Pachuca,...,62.0,23.0,12.0,11.0,70.0,64.0,65.0,73.0,74.0,€272K
18183,18183,53748,K. Pilkington,44,https://cdn.sofifa.org/players/4/19/53748.png,England,https://cdn.sofifa.org/flags/14.png,48,48,Cambridge United,...,56.0,15.0,15.0,13.0,45.0,48.0,44.0,49.0,46.0,NaN
17726,17726,51963,T. Warner,44,https://cdn.sofifa.org/players/4/19/51963.png,Trinidad & Tobago,https://cdn.sofifa.org/flags/93.png,53,53,Accrington Stanley,...,46.0,19.0,15.0,14.0,48.0,56.0,56.0,60.0,44.0,NaN
10545,10545,140183,S. Narazaki,42,https://cdn.sofifa.org/players/4/19/140183.png,Japan,https://cdn.sofifa.org/flags/163.png,65,65,Nagoya Grampus,...,45.0,27.0,24.0,22.0,64.0,63.0,62.0,67.0,63.0,€50K
7225,7225,142998,C. Muñoz,41,https://cdn.sofifa.org/players/4/19/142998.png,Argentina,https://cdn.sofifa.org/flags/52.png,68,68,CD Universidad de Concepción,...,62.0,18.0,14.0,19.0,67.0,65.0,68.0,71.0,68.0,€84K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17921,17921,246601,J. Rowland,16,https://cdn.sofifa.org/players/4/19/246601.png,England,https://cdn.sofifa.org/flags/14.png,51,66,Shrewsbury,...,52.0,36.0,31.0,30.0,12.0,10.0,7.0,6.0,12.0,€166K
17887,17887,246009,M. Tilio,16,https://cdn.sofifa.org/players/4/19/246009.png,Australia,https://cdn.sofifa.org/flags/195.png,52,69,Sydney FC,...,47.0,31.0,35.0,47.0,12.0,7.0,13.0,14.0,14.0,€188K
15363,15363,245015,Y. Roemer,16,https://cdn.sofifa.org/players/4/19/245015.png,Netherlands,https://cdn.sofifa.org/flags/34.png,59,75,VVV-Venlo,...,48.0,22.0,15.0,20.0,9.0,9.0,11.0,10.0,9.0,€623K
17881,17881,242165,R. Hauge,16,https://cdn.sofifa.org/players/4/19/242165.png,Norway,https://cdn.sofifa.org/flags/36.png,52,67,FK Bodø/Glimt,...,48.0,48.0,50.0,47.0,6.0,9.0,11.0,11.0,9.0,€188K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

EJERCICIO

tomar solo onmbres, salarios y valores de los jugadores

In [56]:
data_frame.loc[1:10, ['Name', 'Value', 'Wage']]

                 Name    Value   Wage
1   Cristiano Ronaldo     €77M  €405K
2           Neymar Jr  €118.5M  €290K
3              De Gea     €72M  €260K
4        K. De Bruyne    €102M  €355K
5           E. Hazard     €93M  €340K
6           L. Modrić     €67M  €420K
7           L. Suárez     €80M  €455K
8        Sergio Ramos     €51M  €380K
9            J. Oblak     €68M   €94K
10     R. Lewandowski     €77M  €205K

In [61]:
new_df = pd.DataFrame(data_frame, columns=['Name', 'Value', 'Wage'])

def value_to_float(x):
    if type(x) == float or type(x) == int:
        return x
    if 'K' in x:
        if len(x) > 1:
            return float(x.replace('K', '')) * 1000
        return 1000.0
    if 'M' in x:
        if len(x) > 1:
            return float(x.replace('M', '')) * 1000000
        return 1000000.0
    if 'B' in x:
        return float(x.replace('B', '')) * 1000000000
    return 0.0

wage = new_df['Wage'].replace('[\€,]', '', regex=True).apply(value_to_float)
value = new_df['Value'].replace('[\€,]', '', regex=True).apply(value_to_float)
new_df['Wage']=wage
new_df['Value']=value

                     Name    Value   Wage
0                L. Messi  €110.5M  €565K
1       Cristiano Ronaldo     €77M  €405K
2               Neymar Jr  €118.5M  €290K
3                  De Gea     €72M  €260K
4            K. De Bruyne    €102M  €355K
...                   ...      ...    ...
18202        J. Lundstram     €60K    €1K
18203  N. Christoffersson     €60K    €1K
18204           B. Worman     €60K    €1K
18205      D. Walker-Rice     €60K    €1K
18206           G. Nugent     €60K    €1K

[18207 rows x 3 columns]